# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: sohelsaiyed/my-app
  pullPolicy: Always
  tag: "1.0"
  ports:
    name: http
    containerPort: 80
    protocol: TCP

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  protocol: TCP
  name: http

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: example.local
      paths: [/my-app]


